# Generated by Django 2.2 on 2019-04-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_data',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sn_num', models.CharField(default='', max_length=255)),
                ('remark', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
