# Generated by Django 2.2 on 2019-04-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_service_data_posi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_cmdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_key', models.CharField(max_length=50)),
                ('set_value', models.CharField(max_length=50)),
            ],
        ),
    ]
