# Generated by Django 2.2 on 2019-04-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_settings_cmdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings_cmdb',
        ),
    ]
