# Generated by Django 2.2 on 2019-04-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_delete_settings_cmdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_cmdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50)),
            ],
        ),
    ]
