# Generated by Django 2.2 on 2019-04-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_settings_cmdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings_cmdb',
            name='site_name',
            field=models.CharField(default='管理平台', max_length=50),
        ),
    ]
