# Generated by Django 2.2 on 2019-04-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_settings_cmdb_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings_cmdb',
            name='user_image',
            field=models.CharField(default='/static/picture/user.png', max_length=50),
        ),
    ]
