# Generated by Django 2.2 on 2019-04-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_settings_cmdb_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_content', models.TextField()),
            ],
        ),
    ]
