# Generated by Django 2.2 on 2019-04-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file_remark',
            field=models.CharField(default='', max_length=200),
        ),
    ]
